source:      .
destination: _site
layouts:     _layouts
keep_files:  ['.git']

future:      true
highlighter: pygments


permalink:     :title
paginate_path: 'page:num'

markdown:      kramdown
markdown_ext:  md

excerpt_separator: "\n\n"

safe:        false
host:        127.0.0.1
port:        4000
lsi:         false
