source:      .
destination: _site
layouts:     _layouts
exclude: [node_modules, README.md, CNAME, package.json, src, .git, dest]

future:      true

permalink:     :title
paginate: 6
paginate_path: "page/:num"

markdown:      kramdown
markdown_ext:  md

defaults:
  is_page: false

excerpt_separator: "\n\n"

safe:        false
host:        127.0.0.1
port:        4000
lsi:         false
